version: '3.1'

services:

  mongo:
    # image: mongo
    build: ./db
    # environment:
    #   - MONGO_INITDB_DATABASE=safechek-db
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=pwd
    volumes:
      # - .data/mdata:/data/db
      - ./db/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - "27017:27017"
    restart: always
    logging:
      driver: none
  
  flask:
    build: ./flask
    ports:
      - "5000:5000"
    environment: 
      - PYTHONUNBUFFERED=1
      # - FLASK_APP=wsgi.py
      # - FLASK_ENV=development
      # - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - ./flask:/app
    depends_on:
      - mongo